// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1yOqNjaJy97DYCbPt2-jGZHF9z0RQNX0',
    appId: '1:116162199423:android:b20887a32fce17a1baa44a',
    messagingSenderId: '116162199423',
    projectId: 'movies-ce65a',
    storageBucket: 'movies-ce65a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-sY1fvmCiE5kGgqqVcqHBxjBDNqck1bY',
    appId: '1:116162199423:ios:cb2ca346c6e8ca1fbaa44a',
    messagingSenderId: '116162199423',
    projectId: 'movies-ce65a',
    storageBucket: 'movies-ce65a.firebasestorage.app',
    androidClientId: '116162199423-qh820m274v3iptehvvqubdko2hgagp1d.apps.googleusercontent.com',
    iosClientId: '116162199423-4aiuu6cb5me6g438q01m17vm8ubjiq87.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

}